language: java

jdk:
  - oraclejdk8

install: true
script:
  - ./mvnw clean install test
  - bash <(curl -s https://codecov.io/bash)

deploy:
    -
    on:
      branch: master
    user: MatheusMatz
    key: $GITHUB_TOKEN
