language: java

jdk:
  - oraclejdk8

install: true
script:
  - ./mvnw clean install test
  - bash <(curl -s https://codecov.io/bash)

deploy:
    -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: target/bin/bintray.json
    user: nfrankel
    key: $BINTRAY_API_KEY
