language: java

jdk:
  - oraclejdk8

install: true
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
